CANVAS_ALL = "all"

LABEL = "Label"
BUTTON = "Button"
GENERAL = "General"
TOOLTIP = "Tooltip"

SPEED_MENU_SLOW = "Slow"
SPEED_MENU_MEDIUM = "Medium"
SPEED_MENU_FAST = "Fast"

END = "end"

LANGUAGE_DE = "de"
LANGUAGE_EN = "en"

BUTTON_TEXT_IMPORT = "Import"
BUTTON_TEXT_EXPORT = "Export"

STATE_READONLY = "readonly"

BUBBLE_SORT = "Bubble Sort"
COUNTING_SORT = "Counting Sort"
HEAP_SORT = "Heap Sort"
INSERTION_SORT = "Insertion Sort"
MERGE_SORT = "Merge Sort"
QUICK_SORT = "Quick Sort"
SELECTION_SORT = "Selection Sort"

DARK_GRAY = '#65696B'
LIGHT_GRAY = '#C4C5BF'
BLUE = '#0CA8F6'
DARK_BLUE = '#4204CC'
WHITE = '#FFFFFF'
BLACK = '#000000'
RED = '#F22810'
YELLOW = '#F7E806'
PINK = '#F50BED'
LIGHT_GREEN = '#05F50E'
PURPLE = '#BF01FB'